# Generated by Django 2.0.5 on 2018-05-25 19:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spot', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('curiosities', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=128, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=128, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
