# Generated by Django 2.0.5 on 2019-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='title',
            field=models.CharField(default='cool image', max_length=1024),
            preserve_default=False,
        ),
    ]
